### PR TITLE
Prioritise recordings with lowest evaluations

### LINKED ISSUE #167: Recordings that do not have (m)any evaluations should be suggested by the evaluator
Similar to how we prioritize verses that don't have many recordings.

### PR DESCRIPTION
**Pull request by AymenQ**
This commit ensures that recordings with the lowest number of
evaluations are suggested for evaluation. Fixes #167.

### CODE REVIEW

**Comment by tifa2UP** [comment]
cc: @abidlabs @piraka9011

**Comment by piraka9011** [comment]
Awesomesauce, thx @AymenQ! Any reason we're not using the built in django ORM methods tho?
Prefer to do that to keep things consistent. `filter()`, [`annotate()`](https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.annotate), and `order_by()` would work here.

**Comment by AymenQ** [comment]
> Awesomesauce, thx @AymenQ! Any reason we're not using the built in django ORM methods tho?
> Prefer to do that to keep things consistent. `filter()`, [`annotate()`](https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.annotate), and `order_by()` would work here.

You're right -- the main reason I used a raw query was because there isn't a foreign key for AnnotatedRecording in Evaluation, so it was a corner cut. I'll try and write a more consistent patch using django ORM methods, and resubmit a pull request soon.

**Comment by AymenQ** [comment]
Delaying this pull request for now since there seems to be multiple versions of the evaluator api, and I'd rather not commit a change to something which isn't in use anymore

**Pull request closed without merging**
